# Generated by Django 4.0.2 on 2022-02-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='gallery',
            field=models.ManyToManyField(related_name='org_gallery', to='organisation.OrgGallery'),
        ),
    ]
